# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# https://community.home-assistant.io/t/how-can-i-manage-the-dashboards-using-yaml-files/538385
# need to restart HA for modifications to become effective
lovelace:
  mode: storage
  dashboards:
    home-dashboard:
      mode: yaml
      title: yaml-test
      show_in_sidebar: true
      filename: gauge.yaml
# https://homeassistant.local:8123/config/energy/dashboard

homeassistant:

  # https://community.home-assistant.io/t/downgrade-from-2024-1-0-docker-compose/666197/3

  # https://www.home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages  # regarding reporting, battery, control, etc.

  # https://www.home-assistant.io/blog/2015/05/09/utc-time-zone-awareness/
  time_zone: CET # Europe/Berlin without DST adaptations

  # needed since 2024.6:
  # https://www.reddit.com/r/homeassistant/comments/1dhw16z/write_to_file_using_notify_from_20246/
  allowlist_external_dirs: # relative paths seem to be based on "/config", which may be mapped to some host file system location
    - "/config/log"
    - "/config"
    - "log"
    - "."

  # https://community.home-assistant.io/t/change-the-color-of-the-icon-of-a-virtual-sensor-depending-of-the-state/338658/14
  # cannot get this installed, so the following is ignored:
  #templates:
  #  icon_color: 'red'

http:
  # SSL certificate and key paths are relative to the Home Assistant configuration directory
  # See: https://www.home-assistant.io/docs/ecosystem/certificates/
  ssl_certificate: cert.pem
  ssl_key: key.pem

## https://github.com/andrey-git/home-assistant-custom-ui?tab=readme-ov-file
#customizer:
#  custom_ui: local

script:   !include scripts.yaml
scene:    !include scenes.yaml
# template: !include template.yaml
