# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# https://community.home-assistant.io/t/how-can-i-manage-the-dashboards-using-yaml-files/538385
# need to restart HA for modifications to become effective
lovelace:
  mode: storage
  dashboards:
    home-dashboard:
      mode: yaml
      title: yaml-test
      show_in_sidebar: true
      filename: gauge.yaml
# https://homeassistant.local:8123/config/energy/dashboard

homeassistant:

  # https://community.home-assistant.io/t/downgrade-from-2024-1-0-docker-compose/666197/3

  # https://www.home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages  # regarding battery, power balance, etc.

  # https://www.home-assistant.io/blog/2015/05/09/utc-time-zone-awareness/
  time_zone: CET # Europe/Berlin without DST adaptations

  # needed since 2024.6:
  # https://www.reddit.com/r/homeassistant/comments/1dhw16z/write_to_file_using_notify_from_20246/
  allowlist_external_dirs: # relative paths seem to be based on "/config", which may be mapped to some host file system location
    - "/config/log"
    - "/config"
    - "log"
    - "."

  # https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize:
    sensor.power_balance:
      # icon: mdi:lightbulb # would override the template sensor icon definition

      # https://community.home-assistant.io/t/how-to-change-icons-colour-of-template-sensor-in-lovelace/107619
      # is ignored, likely due to incomplete installation:
      icon_color: >
        {% set target_charge = states('input_number.target_charge'   )|int(10) %}
        {% set target_dischg = states('input_number.target_discharge')|int(20) %}
        {% set min_balanced = min(target_charge, target_dischg)          - 10  %}
        {% set max_balanced = max(target_charge, target_dischg)          + 10  %}
        {% if   min_balanced       <= this.state|float(0) and this.state|float(0) <= max_balanced       %}
          green
        {% elif min_balanced - 100 <= this.state|float(0) and this.state|float(0) <= max_balanced + 100 %}
          yellow
        {% else %}
          red
        {% endif %}

      # https://community.home-assistant.io/t/change-the-color-of-the-icon-of-a-virtual-sensor-depending-of-the-state/338658/14
      # cannot get this installed, so the following is ignored:
      #templates:
      #  icon_color: 'red'

http:
  # SSL certificate and key paths are relative to the Home Assistant configuration directory
  # See: https://www.home-assistant.io/docs/ecosystem/certificates/
  ssl_certificate: cert.pem
  ssl_key: key.pem

## https://github.com/andrey-git/home-assistant-custom-ui?tab=readme-ov-file
#customizer:
#  custom_ui: local

script:   !include scripts.yaml
scene:    !include scenes.yaml
# template: !include template.yaml


template:
# https://www.home-assistant.io/integrations/template/
# https://smarthomebastler.at/template-sensor-neu-und-effektiv-anlegen/
# https://smarthomeyourself.de/wiki/homeassistant/template-sensoren-von-der-alten-sensor-integration-auf-die-neue-template-integration-umstellen/

  - sensor:
      # derived values needed for Riemann sums (integrations)

      - name: power_consumption
        unique_id: power_consumption_id
        # friendly_name: "Power Consumption"
        device_class: power
        unit_of_measurement: 'W'
        # WTH, variables not supported here - see https://community.home-assistant.io/t/support-variables-in-template-sensors/249082
        availability: >
          {{ is_number(states('sensor.shelly3em_channel_a_power')) and
             is_number(states('sensor.shelly3em_channel_b_power')) and
             is_number(states('sensor.shelly3em_channel_c_power')) }}
        state: >
          {{ max(0, states('sensor.shelly3em_channel_a_power')|float +
                    states('sensor.shelly3em_channel_b_power')|float +
                    states('sensor.shelly3em_channel_c_power')|float +
                    states('sensor.power_production')|float(0) -
                    states('sensor.power_charge'    )|float(0) +
                    states('sensor.power_discharge' )|float(0)) }}
        # not using states('sensor.power_balance'), which partially avoids inconsistencies with earlier values of powA/powB/powC
        # using "max(0, ...)" as workaround for consumption appearing negative because charging jumped high while balance has not been updated yet
        # despite availability, still need to use '|float' to convert the type, see https://github.com/home-assistant/home-assistant.io/issues/30992

      - name: power_import  # on power_balance > 0
        unique_id: power_import_id
        # friendly_name: "Power Import"
        device_class: power
        unit_of_measurement: 'W'
        availability: "{{ is_number(states('sensor.power_balance')) }}"
        state: >
          {{ max(0, states('sensor.power_balance')|float) }}

      - name: power_export  # on power_balance < 0
        unique_id: power_export_id
        # friendly_name: "Power Export"
        device_class: power
        unit_of_measurement: 'W'
        availability: "{{ is_number(states('sensor.power_balance')) }}"
        state: >
          {{ max(0, 0 - states('sensor.power_balance')|float) }}

      - name: power_own_use  # of PV power
        unique_id: power_own_use_id
        # friendly_name: "Power Own Use (self-consumption)"
        device_class: power
        unit_of_measurement: 'W'
        availability: "{{ is_number(states('sensor.power_consumption')) and
                          is_number(states('sensor.power_production' )) and
                          is_number(states('sensor.power_charge'     )) }}"
        state: >
          {{ min(states('sensor.power_consumption')|float,
                 states('sensor.power_production')|float - states('sensor.power_charge')|float) }}
        # may go wrong if consumption and production sensor values are not consistent in time

# https://community.home-assistant.io/t/use-last-value-instead-of-unknown/614331/4
# stable sensors using last known value of base sensor if current value is unknown

  - sensor:
      - name: power_production
        unique_id: power_production
        # friendly_name: "Power Production"  # - stable
        state: "{{ states('sensor.solarflow_800_plus_solar_input_power') }}"
        device_class: power
        unit_of_measurement: W
#       state: '{{ trigger.to_state.state }}'
#   trigger:
#     - platform: state
#       entity_id: sensor.power_production_unstable
#       not_to:
#         - unknown
#         - unavailable

  - sensor:
      - name: power_charge
        unique_id: power_charge
        # friendly_name: "Charge power"  # - stable
        state: "{{ states('sensor.solarflow_800_plus_output_pack_power') }}"
        device_class: power
        unit_of_measurement: W
#       state: '{{ trigger.to_state.state }}'
#   trigger:
#     - platform: state
#       entity_id: sensor.power_charge_unstable
#       not_to:
#         - unknown
#         - unavailable

  - sensor:
      - name: power_discharge
        unique_id: power_discharge
        # friendly_name: "Discharge power"  # - stable
        state: "{{ states('sensor.solarflow_800_plus_pack_input_power') }}"
        device_class: power
        unit_of_measurement: W
#       state: '{{ trigger.to_state.state }}'
#   trigger:
#     - platform: state
#       entity_id: sensor.power_discharge_unstable
#       not_to:
#         - unknown
#         - unavailable

  - sensor:
      - name: power_balance
        unique_id: power_balance_id
        # friendly_name: "Power Balance" # " at distribution box"
        device_class: power
        unit_of_measurement: 'W'
        # WTH, variables not supported here - see https://community.home-assistant.io/t/support-variables-in-template-sensors/249082
        availability: >
          {{ is_number(states('sensor.shelly3em_channel_a_power')) and
             is_number(states('sensor.shelly3em_channel_b_power')) and
             is_number(states('sensor.shelly3em_channel_c_power')) }}
        state: >
          {{ states('sensor.shelly3em_channel_a_power')|float +
             states('sensor.shelly3em_channel_b_power')|float +
             states('sensor.shelly3em_channel_c_power')|float }}
        # https://community.home-assistant.io/t/template-sensor-using-this-variable/420200/4
        # https://www.home-assistant.io/integrations/switch.template/#change-the-icon
        icon: >
          {% set target_charge = states('input_number.target_charge'   )|int(10) %}
          {% set target_dischg = states('input_number.target_discharge')|int(20) %}
          {% set min = min(target_charge, target_dischg)                   - 10  %}
          {% set max = max(target_charge, target_dischg)                   + 10  %}
          {% if min <= this.state|float(0) and this.state|float(0) <= max        %}
            mdi:scale-balance
          {% else %}
            mdi:scale-unbalanced
          {% endif %}

  - sensor:
      - name: "Battery SoC"
        unique_id: battery_soc_id
        state: "{{ states('sensor.solarflow_800_plus_electric_level') }}"
  - sensor:
      - name: "Battery Voltage"
#     - name: battery_voltage
        unique_id: battery_voltage
        state: "{{ states('sensor.solarflow_800_plus_bat_volt') }}"
        unit_of_measurement: V

# sensor: !include sensor.yaml
sensor:
  # need to restart HA for modifications of this list to become effective

    # beware that adding needless derived sensors would be inefficient, see
    # https://www.shelly-support.eu/forum/thread/8977-shelly-3em-phasen-saldieren-in-home-assistant/?postID=218747#post218747

# - platform: template # https://www.home-assistant.io/integrations/template/
#   sensors:
#
#     # workaround for former issue with power production sensor, leading to yields unavailable untility_metervalue with unknown measurement unit
#     energy0_production_hourly:
#       friendly_name: "Energy Production Hourly (workaround)"
#       device_class: energy
#       unit_of_measurement: 'kWh'
#       value_template: >-
#         {{ states('sensor.energy_consumption_hourly')|float(0) - states('sensor.energy_balance_hourly')|float(0) }}
#
#     # workaround for energy export data not always available
#     energy0_export_hourly:
#       friendly_name: "Energy Export Hourly (workaround)"
#       device_class: energy
#       unit_of_measurement: 'kWh'
#       value_template: >-
#         {{ states('sensor.energy_import_hourly')|float(0) - states('sensor.energy_balance_hourly')|float(0) }}

  # https://www.home-assistant.io/integrations/integration/
  # Riemann sums of power values (W) yielding energy (kWh)

  - name: energy_balance_sum
    source: sensor.power_balance
    platform: integration
    unit_prefix: k
    round: 3  # number of digits after comma on output (reading the sum value)
    method: left

  - name: energy_import_sum
    source: sensor.power_import
    platform: integration
    unit_prefix: k
    round: 3
    method: left

  - name: energy_export_sum
    source: sensor.power_export
    platform: integration
    unit_prefix: k
    round: 3
    method: left

  - name: energy_consumption_sum
    source: sensor.power_consumption
    platform: integration
    unit_prefix: k
    round: 3
    method: left

  - name: energy_production_sum
    source: sensor.power_production
    # no need to use float(0) here - see https://github.com/home-assistant/home-assistant.io/issues/30992
    platform: integration
    unit_prefix: k
    round: 3
    method: left

  - name: energy_charge_sum
    source: sensor.power_charge
    # no need to use float(0) here - see https://github.com/home-assistant/home-assistant.io/issues/30992
    platform: integration
    unit_prefix: k
    # The Home battery storage setting at https://homeassistant.local:8123/config/energy/dashboard
    # gives wrong warning: The following entities do not have the expected device class: sensor.energy_charge_sum
    round: 3
    method: left

  - name: energy_discharge_sum
    source: sensor.power_discharge
    # no need to use float(0) here - see https://github.com/home-assistant/home-assistant.io/issues/30992
    platform: integration
    unit_prefix: k
    round: 3
    method: left

  - name: energy_own_use_sum
    source: sensor.power_own_use
    platform: integration
    unit_prefix: k
    round: 3
    method: left

  # Riemann sums of power values (W) yielding energy (Ws)

  - name: power_consumption_sum
    source: sensor.power_consumption
    platform: integration
    unit_time: s  # leads to wrong warning, see https://github.com/home-assistant/core/issues/107223
    round: 2
    method: left

  - name: power_production_sum
    source: sensor.power_production
    platform: integration
    unit_time: s  # leads to wrong warning, see https://github.com/home-assistant/core/issues/107223
    round: 2
    method: left

utility_meter: # https://www.home-assistant.io/integrations/utility_meter/
# energy accumulators that are reset per hour, day, month, or year
# need to restart HA for modifications of this list to become effective

  energy_balance_hourly:
    name: Energy Balance Hourly
    source: sensor.energy_balance_sum
    net_consumption: true
    cycle: hourly
  energy_balance_daily:
    name: Energy Balance Daily
    source: sensor.energy_balance_sum
    net_consumption: true
    cycle: daily
  energy_balance_monthly:
    name: Energy Balance Monthly
    source: sensor.energy_balance_sum
    net_consumption: true
    cycle: monthly
  energy_balance_yearly:
    name: Energy Balance Yearly
    source: sensor.energy_balance_sum
    net_consumption: true
    cycle: yearly

  energy_import_hourly:
    name: Energy Import Hourly
    source: sensor.energy_import_sum
    cycle: hourly
  energy_import_daily:
    name: Energy Import Daily
    source: sensor.energy_import_sum
    cycle: daily
  energy_import_monthly:
    name: Energy Import Monthly
    source: sensor.energy_import_sum
    cycle: monthly
  energy_import_yearly:
    name: Energy Import Yearly
    source: sensor.energy_import_sum
    cycle: yearly

  energy_export_hourly:
    name: Energy Export Hourly
    source: sensor.energy_export_sum
    cycle: hourly
  energy_export_daily:
    name: Energy Export Daily
    source: sensor.energy_export_sum
    cycle: daily
  energy_export_monthly:
    name: Energy Export Monthly
    source: sensor.energy_export_sum
    cycle: monthly
  energy_export_yearly:
    name: Energy Export Yearly
    source: sensor.energy_export_sum
    cycle: yearly

  energy_consumption_hourly:
    name: Energy Consumption Hourly
    source: sensor.energy_consumption_sum
    cycle: hourly
  energy_consumption_daily:
    name: Energy Consumption Daily
    source: sensor.energy_consumption_sum
    cycle: daily
  energy_consumption_monthly:
    name: Energy Consumption Monthly
    source: sensor.energy_consumption_sum
    cycle: monthly
  energy_consumption_yearly:
    name: Energy Consumption Yearly
    source: sensor.energy_consumption_sum
    cycle: yearly

  energy_production_hourly:
    name: Energy Production Hourly  # Statistic id is derived from this: sensor.energy_production_hourly
    source: sensor.energy_production_sum
    net_consumption: true
    cycle: hourly
  energy_production_daily:
    name: Energy Production Daily
    source: sensor.energy_production_sum
    net_consumption: true
    cycle: daily
  energy_production_monthly:
    name: Energy Production Monthly
    source: sensor.energy_production_sum
    net_consumption: true
    cycle: monthly
  energy_production_yearly:
    name: Energy Production Yearly
    source: sensor.energy_production_sum
    net_consumption: true
    cycle: yearly

  energy_charge_hourly:
    name: Energy Charge Hourly
    source: sensor.energy_charge_sum
    net_consumption: true
    cycle: hourly
  energy_charge_daily:
    name: Energy Charge Daily
    source: sensor.energy_charge_sum
    net_consumption: true
    cycle: daily
  energy_charge_monthly:
    name: Energy Charge Monthly
    source: sensor.energy_charge_sum
    net_consumption: true
    cycle: monthly
  energy_charge_yearly:
    name: Energy Charge Yearly
    source: sensor.energy_charge_sum
    net_consumption: true
    cycle: yearly

  energy_discharge_hourly:
    name: Energy Discharge Hourly
    source: sensor.energy_discharge_sum
    net_consumption: true
    cycle: hourly
  energy_discharge_daily:
    name: Energy Discharge Daily
    source: sensor.energy_discharge_sum
    net_consumption: true
    cycle: daily
  energy_discharge_monthly:
    name: Energy Discharge Monthly
    source: sensor.energy_discharge_sum
    net_consumption: true
    cycle: monthly
  energy_discharge_yearly:
    name: Energy Discharge Yearly
    source: sensor.energy_discharge_sum
    net_consumption: true
    cycle: yearly

  energy_own_use_hourly:
    name: Energy Own_Use Hourly
    source: sensor.energy_own_use_sum
    net_consumption: true
    cycle: hourly
  energy_own_use_daily:
    name: Energy Own_Use Daily
    source: sensor.energy_own_use_sum
    net_consumption: true
    cycle: daily
  energy_own_use_monthly:
    name: Energy Own_Use Monthly
    source: sensor.energy_own_use_sum
    net_consumption: true
    cycle: monthly
  energy_own_use_yearly:
    name: Energy Own_Use Yearly
    source: sensor.energy_own_use_sum
    net_consumption: true
    cycle: yearly

  # used to generate load and PV profile:
  energy_consumption_minutely:
    name: Energy Consumption Minutely
    source: sensor.power_consumption_sum
    cron: "* * * * *"
  energy_production_minutely:
    name: Energy Production Minutely
    source: sensor.power_production_sum
    cron: "* * * * *"
