input_number:

  power_balance_avg2: # unused
    name: Power Balance Rolling Average 2
    initial: 0
    min: -999999
    max: +999999
    mode: box

  power_balance_avg: # unused
    name: Power Balance Rolling Average 3
    initial: 0
    min: -999999
    max: +999999
    mode: box

  power_balance_smoothened:
    name: Power Balance Smoothened
    initial: 0
    min: -999999
    max: +999999
    mode: box

  last_channel_a_power:
    name: Last channel A power
    initial: 0
    min: -999999
    max: +999999
    mode: box

  last_channel_b_power:
    name: Last channel B power
    initial: 0
    min: -999999
    max: +999999
    mode: box

  last_channel_c_power:
    name: Last channel C power
    initial: 0
    min: -999999
    max: +999999
    mode: box

  last_channel_a_power_factor:
    name: Last channel A power factor
    initial: 0
    min: -1
    max: 1

  last_channel_b_power_factor:
    name: Last channel B power factor
    initial: 0
    min: -1
    max: 1

  last_channel_c_power_factor:
    name: Last channel C power factor
    initial: 0
    min: -1
    max: 1

  channel_a_power_repeat_len:
    name: channel A power repeat length
    initial: 0
    min: 0
    max: 2

  channel_b_power_repeat_len:
    name: channel B power repeat length
    initial: 0
    min: 0
    max: 2

  channel_c_power_repeat_len:
    name: channel C power repeat length
    initial: 0
    min: 0
    max: 2


automation:

  - id: update_power_balance_avg2 # unused
    initial_state: true
    trigger:
      - platform: time_pattern
        seconds: "/1"
    action:
      # upward rolling average over 2 seconds, used to smoothen peaks in particular on fridge compressor startup
      # https://community.home-assistant.io/t/input-number-moving-average-calculation/453728/1
      # value of platform: statistics would be often 'Unknown' and does not really provide rolling average
      - variables:
          samples: "{{ 2 }}"
          prev   : "{{ states('input_number.power_balance_avg2') }}"
          curr   : "{{ states('sensor.power_balance')| float(0) }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.power_balance_avg2
        data:
          value: "{{ (curr if curr < prev else (prev * (samples-1) + curr) / samples)| round(0) }}"

  - id: update_power_balance_avg # unused
    initial_state: true
    trigger:
      - platform: time_pattern
        seconds: "/1"
    action:
      # upward rolling average over 3 seconds, used to smoothen peaks in particular on fridge compressor startup
      # https://community.home-assistant.io/t/input-number-moving-average-calculation/453728/1
      # value of platform: statistics would be often 'Unknown' and does not really provide rolling average
      - variables:
          samples: "{{ 3 }}"
          prev   : "{{ states('input_number.power_balance_avg') }}"
          curr   : "{{ states('sensor.power_balance')| float(0) }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.power_balance_avg
        data:
          value: "{{ (curr if curr < prev else (prev * (samples-1) + curr) / samples)| round(0) }}"

  # from power balance used for (dis)charge control, filter out inductive power spikes on fridge compressor startup
  - id: update_power_balance_smoothened
    initial_state: true
    trigger:
      - platform: time_pattern
        seconds: "/1"
    action:
      - variables:
          powA:      "{{ states('sensor.shelly3em_channel_a_power'       ) }}"
          powB:      "{{ states('sensor.shelly3em_channel_b_power'       ) }}"
          powC:      "{{ states('sensor.shelly3em_channel_c_power'       ) }}"
          pfA:       "{{ states('sensor.shelly3em_channel_a_power_factor') }}"
          pfB:       "{{ states('sensor.shelly3em_channel_b_power_factor') }}"
          pfC:       "{{ states('sensor.shelly3em_channel_c_power_factor') }}"
          powA_last: "{{ states('input_number.last_channel_a_power'       ) }}"
          powB_last: "{{ states('input_number.last_channel_b_power'       ) }}"
          powC_last: "{{ states('input_number.last_channel_c_power'       ) }}"
          pfA_last:  "{{ states('input_number.last_channel_a_power_factor') }}"
          pfB_last:  "{{ states('input_number.last_channel_b_power_factor') }}"
          pfC_last:  "{{ states('input_number.last_channel_c_power_factor') }}"
          powA_len:  "{{ states('input_number.channel_a_power_repeat_len' ) }}"
          powB_len:  "{{ states('input_number.channel_b_power_repeat_len' ) }}"
          powC_len:  "{{ states('input_number.channel_c_power_repeat_len' ) }}"
          power_threshold:  "{{  300 }}"
          factor_threshold: "{{ 0.02 }}"
          factor_near_1:    "{{ 0.99 }}"
      - condition: "{{ is_number(powA) and is_number(powB) and is_number(powC) and
                       is_number( pfA) and is_number( pfB) and is_number( pfC) }}"
      - variables:
          keepA: "{{ powA_len < 2 and powA >= powA_last + power_threshold * (2 - powA_len) / 2
                     and pfA <= factor_near_1 and (pfA - pfA_last)|abs >= factor_threshold}}"
          keepB: "{{ powB_len < 2 and powB >= powB_last + power_threshold * (2 - powB_len) / 2
                     and pfB <= factor_near_1 and (pfB - pfB_last)|abs >= factor_threshold }}"
          keepC: "{{ powC_len < 2 and powC >= powC_last + power_threshold  * (2 - powC_len) / 2
                     and pfC <= factor_near_1 and (pfC - pfC_last)|abs >= factor_threshold }}"
          powA_smoothened: "{{ powA_last if keepA else powA }}"
          powB_smoothened: "{{ powB_last if keepB else powB }}"
          powC_smoothened: "{{ powC_last if keepC else powC }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.last_channel_a_power
        data:
          value: "{{ powA_smoothened }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.last_channel_a_power_factor
        data:
          value: "{{ pfA_last if keepA else pfA }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.channel_a_power_repeat_len
        data:
          value: "{{ powA_len + 1 if keepA else 0 }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.last_channel_b_power
        data:
          value: "{{ powB_smoothened }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.last_channel_b_power_factor
        data:
          value: "{{ pfB_last if keepB else pfB }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.channel_b_power_repeat_len
        data:
          value: "{{ powB_len + 1 if keepB else 0 }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.last_channel_c_power
        data:
          value: "{{ powC_smoothened }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.last_channel_c_power_factor
        data:
          value: "{{ pfC_last if keepC else pfC }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.channel_c_power_repeat_len
        data:
          value: "{{ powC_len + 1 if keepC else 0 }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.power_balance_smoothened
        data:
          value: "{{ powA_smoothened + powB_smoothened + powC_smoothened }}"
